2025-04-10 16:05:45,371 INFO    MainThread:182680 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-04-10 16:05:45,372 INFO    MainThread:182680 [wandb_setup.py:_flush():67] Configure stats pid to 182680
2025-04-10 16:05:45,372 INFO    MainThread:182680 [wandb_setup.py:_flush():67] Loading settings from /home/user/.config/wandb/settings
2025-04-10 16:05:45,372 INFO    MainThread:182680 [wandb_setup.py:_flush():67] Loading settings from /home/user/Documents/Books/DA24S019_Assignment_2/Part_A/wandb/settings
2025-04-10 16:05:45,372 INFO    MainThread:182680 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-10 16:05:45,372 INFO    MainThread:182680 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/run-20250410_160545-5ojlyvjc/logs/debug.log
2025-04-10 16:05:45,372 INFO    MainThread:182680 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/run-20250410_160545-5ojlyvjc/logs/debug-internal.log
2025-04-10 16:05:45,372 INFO    MainThread:182680 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7d78ba02a5a0>
2025-04-10 16:05:45,373 INFO    MainThread:182680 [wandb_init.py:init():761] calling init triggers
2025-04-10 16:05:45,373 INFO    MainThread:182680 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-10 16:05:45,373 INFO    MainThread:182680 [wandb_init.py:init():784] starting backend
2025-04-10 16:05:45,373 INFO    MainThread:182680 [wandb_init.py:init():788] sending inform_init request
2025-04-10 16:05:45,375 INFO    MainThread:182680 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-10 16:05:45,375 INFO    MainThread:182680 [wandb_init.py:init():803] backend started and connected
2025-04-10 16:05:45,381 INFO    MainThread:182680 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-10 16:05:45,381 INFO    MainThread:182680 [wandb_init.py:init():896] updated telemetry
2025-04-10 16:05:45,387 INFO    MainThread:182680 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-10 16:05:46,031 ERROR   MainThread:182680 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-04-10 16:12:04,359 INFO    MainThread:182680 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/run-20250410_161204-0qfnbfu7/logs/debug.log
2025-04-10 16:12:04,359 INFO    MainThread:182680 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/run-20250410_161204-0qfnbfu7/logs/debug-internal.log
2025-04-10 16:12:04,359 INFO    MainThread:182680 [wandb_init.py:init():761] calling init triggers
2025-04-10 16:12:04,359 INFO    MainThread:182680 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-10 16:12:04,359 INFO    MainThread:182680 [wandb_init.py:init():784] starting backend
2025-04-10 16:12:04,359 INFO    MainThread:182680 [wandb_init.py:init():788] sending inform_init request
2025-04-10 16:12:04,362 INFO    MainThread:182680 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-10 16:12:04,362 INFO    MainThread:182680 [wandb_init.py:init():803] backend started and connected
2025-04-10 16:12:04,368 INFO    MainThread:182680 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-10 16:12:04,368 INFO    MainThread:182680 [wandb_init.py:init():896] updated telemetry
2025-04-10 16:12:04,375 INFO    MainThread:182680 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-10 16:12:05,247 INFO    MainThread:182680 [wandb_init.py:init():995] starting run threads in backend
2025-04-10 16:12:05,540 INFO    MainThread:182680 [wandb_run.py:_console_start():2377] atexit reg
2025-04-10 16:12:05,541 INFO    MainThread:182680 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-10 16:12:05,541 INFO    MainThread:182680 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-10 16:12:05,541 INFO    MainThread:182680 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-10 16:12:05,542 INFO    MainThread:182680 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-10 16:12:05,707 INFO    MainThread:182680 [wandb_run.py:_config_callback():1261] config_cb None None {}
